sudo: required
services:
   - docker

before_install:
   - docker build -t antonv/docker-react -f Dockerfile.dev .

script:
   - docker run antonv/docker-react npm test run -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-west-2"
   app: "docker-react"
   env: "Docker-env"
   bucket_name: 
